/**
 * Smile/smile-provisioner pipeline
 * This uses smile-builder:latest to build smile-provisioner
 * smile-builder comes from ECR
 * XXX: the account id should not be hard coded
 * XXX: nor should the region
 * XXX: Need to generate Jenkinsfile, but you can't with seed jobs
 * XXX: Literally every single other CI platform can fix this
 * XXX: https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/
 */
pipeline {
    triggers {
      upstream(
        upstreamProjects: 'smile-builder',
        threshold: hudson.model.Result.SUCCESS
      )
    }
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/component: smile-builder
    app.kubernetes.io/instance: builder
    app.kubernetes.io/name: smile
spec:
  containers:
    - name: smile-builder
      image: 121789937014.dkr.ecr.us-east-1.amazonaws.com/trexsolutions/smile-builder:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run/docker.sock
          name: docker-sock
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
"""
        }
    }
    stages {
        stage('Checkout') {
          steps {
            git credentialsId: 'jenkins-github', branch: 'main', url: 'https://github.com/trexsolutions/smile-cdk'
          }
        }
        stage('Build smile-provisioner image') {
            steps {
                container('smile-builder') {
                    sh 'bin/smilectl docker_build trexsolutions smile-provisioner $BUILD_NUMBER pipelines/smile-provisioner/Dockerfile'
                }
            }
        }
        stage('ECR Tag smile-provisioner') {
            steps {
                container('smile-builder') {
                    sh 'bin/smilectl docker_tag trexsolutions smile-provisioner $BUILD_NUMBER'
                }
            }
        }
        stage('Push smile-provisioner to ECR') {
            steps {
                container('smile-builder') {
                    sh 'bin/smilectl docker_push trexsolutions smile-provisioner $BUILD_NUMBER'
                }
            }
        }
    }
}
